@startuml class_diagram_overview

' Separator for namespace
set namespaceSeparator ::

' Logging
namespace logging #DDDEEE {
    class Logger {
    }
}
note top of logging: Used by many classes.

' Utils
namespace utils #DDDEEE {
    class CmdLineParser {
    }
}

' Image processing
namespace imageProcessing #DDDEEE {
    class ImageProcManager {
    }
    ImageProcManager ..> ImageReceiver
    ImageProcManager ..> ImagePreprocessing
    ImageProcManager ..> ImageSegmentation
    ImageProcManager ..> ImageProcUtils

    class ImageReceiver {
    }

    class ImagePreprocessing {
    }
    ImagePreprocessing ..> ImageProcUtils

    class ImageSegmentation {
    }

    class ImageProcUtils {
    }
}

' Application
namespace application #DDDEEE {
    class Application {
    }
    Application ..> CommandLineParser
    Application ..> imageProcessing::ImageProcManager

    class CommandLineParser {
    }
    CommandLineParser ..> utils::CmdLineParser
}

@enduml
